---
title: "title"
author: "author"
abstract: "abstract"
header-includes:
   - \usepackage[brazil]{babel}
   - \usepackage{bm}
   - \usepackage{float}
geometry: left=1.7cm, right=1.7cm, top=3cm, bottom=3cm
output:
  bookdown::pdf_document2:
editor_options:
  chunk_output_type: console
indent: true
---



```{r setup, include=F}

options(digits = 3)  
options(scipen = 999)
ggplot2::theme_set(ggplot2::theme_minimal()) 
knitr::opts_chunk$set(echo=F, message=F, warning=F, fig.pos = 'H', 
                      fig.align = 'center', fig.width = 6, fig.height= 3.5)
scale_fill_discrete = \(...) ggplot2::scale_fill_brewer(... , palette = "Set2") 
library(dplyr)
library(magrittr)
```


\section{Section name}
```{r}
masc <- readr::read_csv2('depressao_masculino.csv')
fem <- readr::read_csv2('depressao_feminino.csv')
```


```{r}
idade_mean = masc |> select(`F`, variavel) |> 
  filter(variavel == 'anos') |> group_by(variavel) |> summarise(mean(`F`)) |>
  unlist()
idade_mean = as.numeric(idade_mean[2])
```

```{r}
idade_sd = masc |> select(`F`, variavel) |> 
  filter(variavel == 'anos') |> group_by(variavel) |> summarise(sd(`F`)) |>
  unlist()
idade_sd = as.numeric(idade_sd[2])
```

```{r}
idade_mean + qt(0.975, 13)*idade_sd/sqrt(nrow(masc |> 
                                               filter(variavel == 'anos')))

idade_mean - qt(0.975, 13)*idade_sd/sqrt(nrow(masc |> 
                                               filter(variavel == 'anos')))
```
$$H_0: Trat_{antes} = Trat_{depois}$$
$$H_1: Trat_{antes} < Trat_{depois}$$
```{r}

t.test(masc |> filter(variavel == 'antes') %>% .$`F`, 
       masc |> filter(variavel == 'depois') %>% .$`F`, 
       paired = TRUE)
```

```{r}
masc_antes = masc |> filter(variavel == 'antes') |> group_by(variavel) |> summarise(mean(`F`)) |> unlist()
masc_antes = as.numeric(masc_antes[2])
```

```{r}
masc_depois = masc |> filter(variavel == 'depois') |> group_by(variavel) |> summarise(mean(`F`)) |> unlist()
masc_depois = as.numeric(masc_depois[2])
```

```{r}
dbarra = masc_antes - masc_depois
di =  masc |> filter(variavel == 'antes')%>%.$`F` - masc |> filter(variavel == 'depois')%>%.$`F`
sum(di^2 - length(di)*(dbarra^2))/(length(di)-1)
```


```{r}
(idade_sd * qt(0.975, 13))^2 
```


# Bibliography



